### ISSUE TITLE
./dosmc --prepare fails to build dosmclib because of wasm error with bundled wasm

### ISSUE THREAD

**Issue by keaaw** [pts/owccdos#9] opened 2024-01-16 10:42 UTC
I did a fresh clone of dosmc on Ubuntu 22.04.3 LTS.   `./dosmc --prepare` failed to build dosmclib because the included wasm is erroring out with the message "Error: could not open message resource file.".    Replacing dosmc.dir/wasm with a symlink to open watcom 2.0's binl/wasm fixed the issue and dosmclib built and the examples compile and run.

**Comment by pts** [comment] 2024-02-15 11:32
Thank you for reporting this bug! The root cause is that the `dosmc.dir/wasm.msg` file is missing from https://github.com/pts/dosmc/releases/download/executables-v1/dosmc.dir.linuxi386exec-v1.sfx.7z . I will prepare a new release which includes this file.

**Comment by pts** [comment] 2024-02-15 12:15
Fixed in https://github.com/pts/dosmc/commit/c1df56168328a5f220596f0049ca2b2bd700c3c3 , please pull the change, and try again.

**Closed as completed by pts** 2024-02-15 12:15 UTC
